- name: 创建证书相关目录
  become: true
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - "{{etcd_cert_dir}}"
  - "{{ca_cert_dir}}"

- name: 获取ca证书
  become: true
  copy:
    src: "{{tmp_tls_dir}}/{{item}}"
    dest: "{{ca_cert_dir}}"
  with_items:
  - ca-key.pem
  - ca.pem
  - ca-config.json

- name: 创建 etcd-csr.json
  become: true
  template:
    src: etcd-csr.json.j2
    dest: "{{etcd_cert_dir}}/etcd-csr.json"

- name: 生成etcd证书
  become: true
  shell: "{{bin_dir}}/cfssl gencert -ca={{ca_cert_dir}}/ca.pem \
                     -ca-key={{ca_cert_dir}}/ca-key.pem \
                     -config={{ca_cert_dir}}/ca-config.json \
                     -profile=kubernetes etcd-csr.json | {{bin_dir}}/cfssljson -bare etcd"
  args:
    chdir: "{{etcd_cert_dir}}"